services:
  firat-mongo:
    image: mongo:6
    container_name: firat-mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - bandistack_network
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 })'"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../../../Firat-backend/backend
      dockerfile: Dockerfile
    container_name: firat-backend
    ports:
      - "8000:8000"
    networks:
      - bandistack_network
    depends_on:
      firat-mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:

networks:
  bandistack_network:
    external: true
